const colorsConst = ["red", "green", "yellow", "lightblue", "violet", "brown", "pink", "lightyellow", "aliceblue", "aqua", "lightcyan", "lightcoral", "lightsalmon", 'lightslategray', 'lightseagreen']
let colors = ["red", "green", "yellow", "lightblue", "violet", "brown", "pink", "lightyellow", "aliceblue", "aqua", "lightcyan", "lightcoral", "lightsalmon", 'lightslategray', 'lightseagreen']

function sampleColor() {
    if (colors.length) return colors.splice(Math.floor(Math.random() * colors.length), 1)[0]
    else {
        colors = colorsConst
        return colors.splice(Math.floor(Math.random() * colors.length), 1)[0]
    }
}

let Schedules = [
    [
        {
            Term: 'Spring 2021-2022',
            CRN: '21186',
            Subject: 'EECE',
            Code: '338',
            Section: '1',
            Title: 'Theory of Computation',
            CH: 3,
            BH: 3,
            College: 'EA',
            SeatsT: 15,
            SeatsA: 25,
            BT1: 1100,
            ET1: 1215,
            Buil1: 'BECHTA',
            R1: '111',
            Schedule1: 'TR',
            BT2: null,
            ET2: null,
            Buil2: '.',
            R2: '.',
            Schedule2: '',
            IName: 'Louay',
            ISName: 'Bazzi',
            LCRN: [''],
            LinkedSections: [],
            color: sampleColor()
        },
        {
          Term: 'Spring 2021-2022',
          CRN: '20913',
          Subject: 'CVSP',
          Code: '202',
          Section: '4',
          Title: 'Medieval,Islamic& Renais.civil',
          CH: 3,
          BH: 3,
          College: 'AS',
          SeatsT: 23,
          SeatsA: 0,
          BT1: 930,
          ET1: 1045,
          Buil1: 'NICELY',
          R1: '101',
          Schedule1: 'TR',
          BT2: null,
          ET2: null,
          Buil2: '.',
          R2: '.',
          Schedule2: '',
          IName: 'Tony',
          ISName: 'Nasrallah',
          LCRN: [ '' ],
          LinkedSections: [],
          color: sampleColor() 
        },
        {
            Term: 'Spring 2021-2022',
            CRN: '20995',
            Subject: 'ECON',
            Code: '212',
            Section: 'L3',
            Title: 'Element.Macroeconomics Theory',
            CH: 3,
            BH: 3,
            College: 'AS',
            SeatsT: 80,
            SeatsA: 70,
            BT1: 1530,
            ET1: 1620,
            Buil1: 'WEST',
            R1: 'BATHISH',
            Schedule1: 'TR',
            BT2: null,
            ET2: null,
            Buil2: '.',
            R2: '.',
            Schedule2: '',
            IName: '.',
            ISName: 'STAFF',
            LCRN: ['20979', '20980', '20981', '20982', '20983', '20984'],
            LinkedSections: [[Object], [Object], [Object], [Object], [Object]],
            color: sampleColor()
        },
        {
            Term: 'Spring 2021-2022',
            CRN: '20981',
            Subject: 'ECON',
            Code: '212',
            Section: 'E15',
            Title: 'Element.Macroeconomics Theory',
            CH: 0,
            BH: 0,
            College: 'AS',
            SeatsT: 11,
            SeatsA: 14,
            BT1: 1600,
            ET1: 1650,
            Buil1: 'NICELY',
            R1: '411',
            Schedule1: 'W',
            BT2: null,
            ET2: null,
            Buil2: '.',
            R2: '.',
            Schedule2: '',
            IName: '.',
            ISName: 'STAFF',
            LCRN: ['20995'],
            LinkedSections: [],
            color: sampleColor() 
        },
        {
            Term: 'Spring 2021-2022',
            CRN: '21174',
            Subject: 'EECE',
            Code: '321',
            Section: '1',
            Title: 'Computer Organization',
            CH: 3,
            BH: 3,
            College: 'EA',
            SeatsT: 34,
            SeatsA: 6,
            BT1: 800,
            ET1: 850,
            Buil1: 'BECHTA',
            R1: '107',
            Schedule1: 'MWF',
            BT2: null,
            ET2: null,
            Buil2: '.',
            R2: '.',
            Schedule2: '',
            IName: 'Fatima Al-Zahra',
            ISName: 'Asadallah',
            LCRN: [''],
            LinkedSections: [],
            color: sampleColor() 
        },
        {
            Term: 'Spring 2021-2022',
            CRN: '21178',
            Subject: 'EECE',
            Code: '321L',
            Section: '2',
            Title: 'Computer Organization Laborat.',
            CH: 1,
            BH: 1,
            College: 'EA',
            SeatsT: 17,
            SeatsA: 3,
            BT1: 1400,
            ET1: 1645,
            Buil1: 'IOEC',
            R1: '511',
            Schedule1: 'M',
            BT2: null,
            ET2: null,
            Buil2: '.',
            R2: '.',
            Schedule2: '',
            IName: 'Sara',
            ISName: 'Khaddaj',
            LCRN: [''],
            LinkedSections: [],
            color: sampleColor() 
        },
        {
            Term: 'Spring 2021-2022',
            CRN: '21185',
            Subject: 'EECE',
            Code: '334',
            Section: '1',
            Title: 'Program.Lang.Design&Implement.',
            CH: 3,
            BH: 3,
            College: 'EA',
            SeatsT: 29,
            SeatsA: 11,
            BT1: 800,
            ET1: 915,
            Buil1: 'BECHTA',
            R1: '111',
            Schedule1: 'TR',
            BT2: null,
            ET2: null,
            Buil2: '.',
            R2: '.',
            Schedule2: '',
            IName: '.',
            ISName: 'STAFF',
            LCRN: [''],
            LinkedSections: [],
            color: sampleColor() 
        },
        {
            Term: 'Spring 2021-2022',
            CRN: '21188',
            Subject: 'EECE',
            Code: '340',
            Section: '2',
            Title: 'Signals and Systems',
            CH: 3,
            BH: 3,
            College: 'EA',
            SeatsT: 22,
            SeatsA: 18,
            BT1: 1000,
            ET1: 1050,
            Buil1: 'BECHTA',
            R1: '205',
            Schedule1: 'MWF',
            BT2: null,
            ET2: null,
            Buil2: '.',
            R2: '.',
            Schedule2: '',
            IName: 'Ibrahim',
            ISName: 'Abou Faycal',
            LCRN: [''],
            LinkedSections: [],
            color: sampleColor() 
        },
        {
            Term: 'Spring 2021-2022',
            CRN: '21192',
            Subject: 'EECE',
            Code: '350',
            Section: '2',
            Title: 'Computer Networks',
            CH: 3,
            BH: 3,
            College: 'EA',
            SeatsT: 42,
            SeatsA: -2,
            BT1: 900,
            ET1: 950,
            Buil1: 'BECHTA',
            R1: '109',
            Schedule1: 'MWF',
            BT2: null,
            ET2: null,
            Buil2: '.',
            R2: '.',
            Schedule2: '',
            IName: 'Imad',
            ISName: 'Elhajj',
            LCRN: [''],
            LinkedSections: [],
            color: sampleColor() 
        },
        {
            Term: 'Spring 2021-2022',
            CRN: '21394',
            Subject: 'ENGL',
            Code: '206',
            Section: '7',
            Title: 'Technical English',
            CH: 3,
            BH: 3,
            College: 'AS',
            SeatsT: 17,
            SeatsA: 8,
            BT1: 1100,
            ET1: 1150,
            Buil1: 'REYNOL',
            R1: '414',
            Schedule1: 'MWF',
            BT2: null,
            ET2: null,
            Buil2: '.',
            R2: '.',
            Schedule2: '',
            IName: 'Malaki',
            ISName: 'Khoury',
            LCRN: [''],
            LinkedSections: [],
            color: sampleColor() 
        }
    ],
    [
        {
            Term: '202220',
            CRN: '21175',
            Subject: 'EECE',
            Code: '321',
            Section: '2',
            Title: 'Computer Organization',
            CH: 3,
            BH: 3,
            College: 'EA',
            SeatsT: 42,
            SeatsA: -2,
            BT1: 900,
            ET1: 950,
            Buil1: 'BECHTA',
            R1: '107',
            Schedule1: 'MWF',
            BT2: null,
            ET2: null,
            Buil2: '.',
            R2: '.',
            Schedule2: '',
            IName: 'Mazen',
            ISName: 'Saghir',
            LCRN: [Array],
            LinkedSections: [],
            color: sampleColor() 
        },
        {
            Term: '202220',
            CRN: '21178',
            Subject: 'EECE',
            Code: '321L',
            Section: '2',
            Title: 'Computer Organization Laborat.',
            CH: 1,
            BH: 1,
            College: 'EA',
            SeatsT: 17,
            SeatsA: 3,
            BT1: 1400,
            ET1: 1645,
            Buil1: 'IOEC',
            R1: '511',
            Schedule1: 'M',
            BT2: null,
            ET2: null,
            Buil2: '.',
            R2: '.',
            Schedule2: '',
            IName: 'Sara',
            ISName: 'Khaddaj',
            LCRN: [Array],
            LinkedSections: [],
            color: sampleColor() 
        },
        {
            Term: '202220',
            CRN: '21185',
            Subject: 'EECE',
            Code: '334',
            Section: '1',
            Title: 'Program.Lang.Design&Implement.',
            CH: 3,
            BH: 3,
            College: 'EA',
            SeatsT: 29,
            SeatsA: 11,
            BT1: 800,
            ET1: 915,
            Buil1: 'BECHTA',
            R1: '111',
            Schedule1: 'TR',
            BT2: null,
            ET2: null,
            Buil2: '.',
            R2: '.',
            Schedule2: '',
            IName: '.',
            ISName: 'STAFF',
            LCRN: [Array],
            LinkedSections: [],
            color: sampleColor() 
        },
        {
            Term: '202220',
            CRN: '21186',
            Subject: 'EECE',
            Code: '338',
            Section: '1',
            Title: 'Theory of Computation',
            CH: 3,
            BH: 3,
            College: 'EA',
            SeatsT: 15,
            SeatsA: 25,
            BT1: 1100,
            ET1: 1215,
            Buil1: 'BECHTA',
            R1: '111',
            Schedule1: 'TR',
            BT2: null,
            ET2: null,
            Buil2: '.',
            R2: '.',
            Schedule2: '',
            IName: 'Louay',
            ISName: 'Bazzi',
            LCRN: [Array],
            LinkedSections: [],
            color: sampleColor() 
        },
        {
            Term: '202220',
            CRN: '21388',
            Subject: 'ENGL',
            Code: '206',
            Section: '1',
            Title: 'Technical English',
            CH: 3,
            BH: 3,
            College: 'AS',
            SeatsT: 25,
            SeatsA: 0,
            BT1: 930,
            ET1: 1045,
            Buil1: 'REYNOL',
            R1: '414',
            Schedule1: 'TR',
            BT2: null,
            ET2: null,
            Buil2: '.',
            R2: '.',
            Schedule2: '',
            IName: 'Abir',
            ISName: 'Ward',
            LCRN: [Array],
            LinkedSections: [],
            color: sampleColor() 
        },
        {
            Term: '202220',
            CRN: '21719',
            Subject: 'INDE',
            Code: '301',
            Section: '1',
            Title: 'Engineering Economy',
            CH: 3,
            BH: 3,
            College: 'EA',
            SeatsT: 44,
            SeatsA: 1,
            BT1: 1100,
            ET1: 1150,
            Buil1: 'BECHTA',
            R1: '204',
            Schedule1: 'MWF',
            BT2: null,
            ET2: null,
            Buil2: '.',
            R2: '.',
            Schedule2: '',
            IName: '.',
            ISName: 'STAFF',
            LCRN: [Array],
            LinkedSections: [],
            color: sampleColor() 
        },
        {
            Term: '202220',
            CRN: '21855',
            Subject: 'MATH',
            Code: '227',
            Section: '1',
            Title: 'Intro to Complex Analysis',
            CH: 3,
            BH: 3,
            College: 'AS',
            SeatsT: 15,
            SeatsA: 10,
            BT1: 800,
            ET1: 850,
            Buil1: 'NICELY',
            R1: '214',
            Schedule1: 'MWF',
            BT2: null,
            ET2: null,
            Buil2: '.',
            R2: '.',
            Schedule2: '',
            IName: 'Tamer',
            ISName: 'Tlas',
            LCRN: [],
            LinkedSections: [],
            color: sampleColor() 
        }
    ]
]

module.exports.Schedules = Schedules